# Generated by Django 6.0.7 on 2026-08-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=32)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('shipment_status', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.company')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('order_line_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('fulfillment_status', models.CharField(max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.order')),
            ],
            options={
                'ordering': ['order_line_id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateField()),
                ('valid_until', models.DateField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='quotes.quote'),
        ),
        migrations.CreateModel(
            name='QuoteRevision',
            fields=[
                ('quote_revision_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveSmallIntegerField()),
                ('revision_status', models.CharField(max_length=32)),
                ('issued_at', models.DateField()),
                ('discount_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('change_summary', models.TextField()),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='quotes.quote')),
            ],
            options={
                'ordering': ['quote', 'revision_number'],
                'unique_together': {('quote', 'revision_number')},
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('quote_line_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='machines.machine')),
                ('quote_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quoterevision')),
            ],
            options={
                'ordering': ['quote_line_id'],
            },
        ),
    ]
