# Generated by Django 6.0.7 on 2026-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=128)),
                ('sector', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=3)),
                ('locale', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['company_name'],
            },
        ),
    ]
