# Generated by Django 6.0.7 on 2026-08-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('model_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('model_code', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('primitive_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('nominal_heads', models.PositiveSmallIntegerField()),
                ('container_type', models.CharField(max_length=256)),
                ('cap_type', models.CharField(max_length=256)),
                ('industry_segment', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['model_code'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('delivery_date', models.DateField()),
                ('plant_location', models.CharField(max_length=256)),
                ('configuration_profile', models.TextField()),
                ('plc_family', models.CharField(max_length=128)),
                ('software_version', models.CharField(blank=True, default='', max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.company')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.machinemodel')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarm_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('alarm_code', models.CharField(max_length=128)),
                ('severity', models.CharField(max_length=16)),
                ('alarm_status', models.CharField(max_length=32)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='machines.machine')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('ticket_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(max_length=64)),
                ('ticket_status', models.CharField(max_length=32)),
                ('priority', models.CharField(max_length=16)),
                ('created_date', models.DateField()),
                ('owner_role', models.CharField(max_length=64)),
                ('alarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='machines.alarm')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='MachineUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_units', to='machines.machine')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
                'unique_together': {('machine', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('telemetry_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('operational_status', models.CharField(max_length=32)),
                ('production_rate_bph', models.PositiveIntegerField()),
                ('uptime_percentage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('alarm_count', models.PositiveSmallIntegerField()),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('energy_kwh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('health_note', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshots', to='machines.machine')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', 'timestamp'], name='machines_te_machine_2320d8_idx')],
            },
        ),
    ]
