# Generated by Django 6.0.7 on 2026-07-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('qr_token', models.CharField(blank=True, default='', help_text='Token encoded in on-machine QR codes for lookup.', max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('full_model', models.CharField(max_length=256)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('manufacturer', models.CharField(default='AROL S.p.A.', max_length=128)),
                ('site', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField()),
                ('machine_type', models.CharField(max_length=256)),
                ('pitch_diameter', models.CharField(max_length=64)),
                ('heads', models.PositiveSmallIntegerField(default=1)),
                ('rotation', models.CharField(max_length=64)),
                ('manual_revision', models.CharField(blank=True, default='', max_length=32)),
                ('manual_date', models.CharField(blank=True, default='', max_length=32)),
                ('manual_url', models.CharField(blank=True, default='', max_length=512)),
                ('weight_value', models.CharField(max_length=32)),
                ('weight_unit', models.CharField(default='kg', max_length=16)),
                ('productive_capacity_value', models.CharField(max_length=32)),
                ('productive_capacity_unit', models.CharField(default='pcs/h', max_length=32)),
                ('electrical_main_supply', models.CharField(max_length=128)),
                ('electrical_auxiliary_supply', models.CharField(max_length=128)),
                ('electrical_total_installed_power', models.CharField(max_length=64)),
                ('electrical_breakdown', models.JSONField(blank=True, default=list, help_text='List of {"label": "...", "value": "..."} power breakdown rows.')),
                ('pneumatic_sterile_air_capacity', models.CharField(max_length=64)),
                ('pneumatic_min_pressure', models.CharField(max_length=32)),
                ('pneumatic_max_pressure', models.CharField(max_length=32)),
                ('operating_temperature', models.CharField(max_length=128)),
                ('operating_environment', models.TextField()),
                ('operating_noise', models.TextField()),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certification strings, e.g. ["CE", "Directive 2006/42/EC"].')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Customer/user that owns this machine (tenant scope).', on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='MachineUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_units', to='machines.machine')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
                'unique_together': {('machine', 'code')},
            },
        ),
    ]
